# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64c9702cea1eff60afb520a41b1721abc3e91b276c9b8d3c098058b99f9f0a3456d2eb57ce4e058c639ff160c6002ebe76e837288cfd1d8b392870214d2c05b8

test:
  secret_key_base: b5c93a7d8b42b8f4ea12b389700a28458aa6961515ad5d2af40241c9660ad0c05e4e76edad06c9ab200afbce6a112abfdf297842c1e2ddcba350e988a55012c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
